### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by StaticRocket** [rupor-github/squid#1]
```
SquidSrv.exe - Application Error
The service was unable to start correctly (0xc000007b).
```
Prompted when running `SquidSrv.exe -install` in an elevated command line interface with `cpuidsdk.dll` and `SiUSBXp.dll`, extracted from the most recent version of CAM, in the same directory. Can this be run successfully with the Kraken x62?

**Comment by rupor-github** [comment]
I could only validate it with Kraken X41/X61 - I do not have X62 hardware to test it.

**Comment by StaticRocket** [comment]
Well then, I have an x62 and am currently experiencing the above issue. Do you have any advice or any things you want me to verify?

**Comment by rupor-github** [comment]
Well, when working with X61 I kind of reverse engineered CAM v3.0 and "extracted" what they do with device via USB interface. My understanding is that this algorithm should be device specific (and may be very device specific if different controller is being used on X62). According to what I could google "The X62 has a few features that kinda put the X61 to shame. Better RGB Effects, separate controls for pump and radiator fans, new radiator fans, and an improved pump". This makes me think that controller is very different. Also each version of cpuid SDK uses "protection" which is based on SDK version - functions to be called simply have different names. Unless you are willing to perform the same level of investigation I did - I do not see how to help you. And if you are - I do not think you need my help at all :)

**Comment by StaticRocket** [comment]
Wonderful, thanks for the jump-start. I'm currently fighting with my Windows partition on my laptop, but when I get done with that I will probably end up trying to make some form of control application for this. Would you be interested in having my control system merge with your project, considering I kind of like what you have setup and will probably be using it for reference?

**Comment by rupor-github** [comment]
Sure, let's see what you will come up with! You could start by forking my code - it is open for a reason.
