### ISSUE TITLE
Could you please make the latest version when you are free?

### ISSUE THREAD

**Issue by marsgovernor** [rupor-github/squid#2]
Is the latest version of the cpuidsdk still applicable? What should I do if I want to call newest cpuidsdk to read the temperature of the CPU and the fan connected to the motherboard? Could you give me some advice? Could you please make the latest version when you are free? Thank you very much.

**Comment by marsgovernor** [comment]
I searched the whole Internet and found that only you can directly call this DLL(cpuidsdk.dll). It's absolutely amazing!
In addition, cpuidsdk is also used here. https://benchmarks.ul.com/systeminfo

**Comment by rupor-github** [comment]
I am sorry - I do not have computer to install this on any longer. In the middle of COVID motherboard died (after 5 and a half years) and I build myself another rig using Fractal Design Celsius+ S28. So I am affraid I cannot help you here,
